---
title: "Package Demo with HeartSteps"
output: html_document
---
 
```{r knit-setup, include = FALSE}
knitr::opts_chunk$set(
collapse = TRUE,
comment = "#>"
)
```

```{r setup}
library(mrt.dose)
```

# Simulate some data

Most simple case

```{r sim}
m=5; n=c(5,10,15); time=5; days=6; eta=c(0,0,0,0); rho=0; 
theta1=c(0,0,0); theta2=0; beta10=1; beta11=0; beta12=0; p=0.5; dose=1

rslt <- matrix(NA, nrow=length(n), ncol=3)
for (i in 1:3) {
  df.corr <- simMhealth(m, n[i], time, days, eta, rho, theta1, theta2, beta10, beta11, beta12, p)
  rslt[i,] <- c(n[i], get.sim.rslts2(m, dfs=df.corr, id="ID", day="DAY", slot="SLOT", p, dose=dose, y="Y", trt="A",
                                     print_progress=FALSE))
}
rslt
```

Misspecified baseline, no time-varying covariate

```{r sim-2}
m=10; n=c(100,200,300); time=5; days=6; eta=c(4,3,2,1); rho=0; 
theta1=c(0,0,0); theta2=0; beta10=1; beta11=0; beta12=0; p=0.5; dose=1

rslt2 <- matrix(NA, nrow=length(n), ncol=3)
for (i in 1:3) {
  df.corr <- simMhealth(m, n[i], time, days, eta, rho, theta1, theta2, beta10, beta11, beta12, p)
  rslt2[i,] <- c(n[i], get.sim.rslts2(m, dfs=df.corr, id="ID", day="DAY", slot="SLOT", p, dose=dose, y="Y", trt="A",
                                      baseline=c("H1", "H2"), print_progress=FALSE))
}
rslt2
```

Misspecified baseline, correctly specified time-varying covariate

```{r sim-3}
m=10; n=c(10,20,30); time=5; days=6; eta=c(4,3,2,1); rho=0.5; 
theta1=c(3,2,1); theta2=0; beta10=1; beta11=c(0.5,0.5); beta12=c(0.3,0.3); p=0.5; dose=1

rslt3 <- NULL
for (i in 1:1) {
  df.corr <- simMhealth(m, n[i], time, days, eta, rho, theta1, theta2, beta10, beta11, beta12, p)
  rslt3 <- rbind(rslt3,c(n[i], get.sim.rslts2(m, dfs=df.corr, id="ID", day="DAY", slot="SLOT", p, 
                                      dose=dose, y="Y", trt="A", 
                                      baseline=c("H1", "H2"), timevar=c("S1", "S2"),
                                      b.prime=c("H1", "H2"), t.prime=c("S1", "S2"),
                                      print_progress=FALSE)))
}
rslt3
```

Similar to HeartSteps. Replicating Previous results
```{r}
m=100; n=100; time=5; days=42; eta=c(1,20,10,30); rho=0.5;
theta1=c(0,0,0); theta2=0; beta10=20; beta11=c(10, 5, 0); beta12=0; p=0.5; dose=1
dfs <- simMhealth(m, n, time, days, eta, rho, theta1, theta2, beta10, beta11, beta12, p)
fits <- mHealthDoses(dfs, id="ID", day="DAY", slot="SLOT", p, 
                   doses=c(1,2,3,4,5), y="Y", trt="A",
                   baseline=c("H1","H2"), 
                   b.prime=c("H1", "H2"),
                  boot = m, cores = 2, sim=TRUE, print_progress=FALSE)
summary(fits)
```

